export { registerStockRoutes } from '../Modules/Stock/Routes'
export { registerFoodRoutes } from '../Modules/Food/Routes'
export { registerRHRoutes } from '../Modules/RH/Routes'
// export { rhRoutes } from './rh'
export { clienteRoutes } from './cliente'
export { itemPedidoRoutes } from './item_pedido'
export { pedidoRoutes } from './pedido'
export { vendaSaidaRoutes } from './venda_saida'
export { lancamentoRoutes } from './lancamento'
export { notaFiscalRoutes } from './notafiscal'
export { caixaRoutes } from './caixa'
export { permissaoRoutes } from './permissao'
export { movimentacaoCaixaRoutes } from './movimentacao_caixa'
export { dashboardRoutes } from './dashboard'
export { alimentosEntradaRoutes } from './alimentos_entrada'
export { alimentosSaidaRoutes } from './alimentos_saida'
