export { registerStockRoutes } from "../Modules/Stock/Routes";
export { rhRoutes } from "./rh";
export { clienteRoutes } from "./cliente";
export { itemPedidoRoutes } from "./item_pedido";
export { pedidoRoutes } from "./pedido";
export { vendaSaidaRoutes } from "./venda_saida";
export { lancamentoRoutes } from "./lancamento";
export { notaFiscalRoutes } from "./notafiscal";
export { caixaRoutes } from "./caixa";
